feat: update libgpg-error to 1.47

diff --git a/src/gpgrt-config.in b/src/gpgrt-config.in
--- a/src/gpgrt-config.in
+++ b/src/gpgrt-config.in
@@ -1,5 +1,6 @@
 #!@INSTALLSHELLPATH@
-# Copyright (C) 2018, 2021 g10 Code GmbH
+#                          -*- mode: shell-script; sh-shell: "/bin/sh" -*-
+# Copyright (C) 2018, 2021, 2022 g10 Code GmbH
 #
 # This file is free software; as a special exception the author gives
 # unlimited permission to copy and/or distribute it, with or without
@@ -41,7 +42,7 @@ get_attr () {
 
 # variant of get_attr for list (separated by ',')
 get_attr_l () {
-    (IFS=', '; for x in "$(get_attr $1)"; do echo $x; done)
+    (IFS=', '; echo "$(get_attr $1)")
 }
 
 # Remove ${varname} part in the beginning of a string.
@@ -192,9 +193,14 @@ list_only_once () {
     __arg=""
 
     for __arg; do
-	if not_listed_yet $__arg $__result; then
-	    __result="$__result${__result:+ }$__arg"
-	fi
+	case "$__arg" in
+	    -I/usr/include|-I/include) ;;
+	    *)
+                if not_listed_yet $__arg $__result; then
+	            __result="$__result${__result:+ }$__arg"
+	        fi
+                ;;
+	esac
     done
 
     echo $__result
@@ -209,6 +215,7 @@ list_only_once_for_libs () {
     # the resulted list is in reverse order
     for __arg; do
 	case "$__arg" in
+	    -L/usr/lib|-L/usr/lib64|-L/lib|-L/lib64) ;;
 	    -l*)
 		# As-is
 		__rev_list="$__arg${__rev_list:+ }$__rev_list"
@@ -445,6 +452,71 @@ Options:
 EOF
     exit $1
 }
+
+# Determine gpgrt_libdir
+determine_gpgrt_libdir () {
+    GPGRT_CONFIG="$0"
+    #
+    # Get the prefix of gpgrt-config assuming it's something like:
+    #   <PREFIX>/bin/gpgrt-config
+    gpgrt_prefix=${GPGRT_CONFIG%/*/*}
+    possible_libdir1=${gpgrt_prefix}/lib
+    # Determine by using system libdir-format with CC, it's like:
+    #   Normal style: /usr/lib
+    #   GNU cross style: /usr/<triplet>/lib
+    #   Debian style: /usr/lib/<multiarch-name>
+    #   Fedora/openSUSE style: /usr/lib, /usr/lib32 or /usr/lib64
+    # It is assumed that CC is specified to the one of host on cross build.
+    if libdir_candidates=$(${CC:-cc} -print-search-dirs | \
+          sed -n -e "/^libraries/{s/libraries: =//;s/:/\\
+/g;p;}"); then
+      # From the output of -print-search-dirs, select valid pkgconfig dirs.
+      libdir_candidates=$(for dir in $libdir_candidates; do
+        if p=$(cd $dir 2>/dev/null && pwd); then
+          test -d "$p/pkgconfig" && echo $p;
+        fi
+      done)
+
+      for possible_libdir0 in $libdir_candidates; do
+        # possible_libdir0:
+        #   Fallback candidate, the one of system-installed (by $CC)
+        #   (/usr/<triplet>/lib, /usr/lib/<multiarch-name> or /usr/lib32)
+        # possible_libdir1:
+        #   Another candidate, user-locally-installed
+        #   (<gpgrt_prefix>/lib)
+        # possible_libdir2
+        #   Most preferred
+        #   (<gpgrt_prefix>/<triplet>/lib,
+        #    <gpgrt_prefix>/lib/<multiarch-name> or <gpgrt_prefix>/lib32)
+        if test "${possible_libdir0##*/}" = "lib"; then
+          possible_prefix0=${possible_libdir0%/lib}
+          possible_prefix0_triplet=${possible_prefix0##*/}
+          if test -z "$possible_prefix0_triplet"; then
+            continue
+          fi
+          possible_libdir2=${gpgrt_prefix}/$possible_prefix0_triplet/lib
+        else
+          possible_prefix0=${possible_libdir0%%/lib*}
+          possible_libdir2=${gpgrt_prefix}${possible_libdir0#$possible_prefix0}
+        fi
+        if test -f ${possible_libdir2}/pkgconfig/gpg-error.pc; then
+          gpgrt_libdir=${possible_libdir2}
+        elif test -f ${possible_libdir1}/pkgconfig/gpg-error.pc; then
+          gpgrt_libdir=${possible_libdir1}
+        elif test -f ${possible_libdir0}/pkgconfig/gpg-error.pc; then
+          gpgrt_libdir=${possible_libdir0}
+        fi
+        if test -n "$gpgrt_libdir"; then break; fi
+      done
+      if test -z "$libdir_candidates"; then
+        # No valid pkgconfig dir in any of the system directories, fallback
+        gpgrt_libdir=${possible_libdir1}
+      fi
+    else
+      # When we cannot determine system libdir-format, use this:
+      gpgrt_libdir=${possible_libdir1}
+    fi
+}
 #### end of functions for this script
 
 myname=${0##*/}
@@ -469,7 +541,7 @@ while test $# -gt 0; do
     esac
 done
 
-if [ x"${PKG_CONFIG_LIBDIR:+set}" = xset -a -z "$PKG_CONFIG_LIBDIR" ]; then
+if env | grep '^PKG_CONFIG_LIBDIR=$' >/dev/null 2>&1; then
   # The variable set as empty, we use PKG_CONFIG_PATH in this case,
   # ignoring --libdir option
   if [ -z "$PKG_CONFIG_PATH"  ]; then
@@ -483,9 +555,14 @@ else
   fi
   if [ -z "$PKG_CONFIG_LIBDIR" ]; then
     if [ -z "$PKG_CONFIG_PATH" ]; then
-      echo "Please use --libdir=LIBDIR option or set PKG_CONFIG_LIBDIR" 1>&2
-      echo "Or set PKG_CONFIG_PATH" 1>&2
-      exit 1
+      # It used to fail as:
+      #
+      # echo "Please use --libdir=LIBDIR option or set PKG_CONFIG_LIBDIR" 1>&2
+      # echo "Or set PKG_CONFIG_PATH" 1>&2
+      #
+      # Now, we try a fallback.
+      determine_gpgrt_libdir
+      PKG_CONFIG_PATH="${gpgrt_libdir}/pkgconfig"
     fi
   else
     # PKG_CONFIG_LIBDIR is available here
